name: Setup node and install dependencies
description: Setups node and installs all dependencies with npm cache

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
