name: 'Semantic Release'
description: 'Handle versioning and CHANGELOG generation'

inputs:
  github-token:
    description: 'The GitHub token to use for authentication'
    required: true
  npm-token:
    description: 'The npm token to use for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Semantic Release
      run: npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
