name: Check PR to main branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr-to-main:
    name: Check PR to main branch
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Check code for errors
        uses: ./.github/actions/check-code

      - name: Checks test coverage
        uses: ./.github/actions/test-coverage
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          coverage-comment: 'true'
