name: 'Semantic Release'

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents:	write
      deployments: write
      id-token:	write
      issues: write
      packages:	write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses:	write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node and install dependencies
        uses: ./.github/actions/setup-node

      - name: Check code for errors
        uses: ./.github/actions/check-code

      - name: Checks test coverage
        uses: ./.github/actions/test-coverage
        with:
          token: ${{ github.token }}
          coverage-comment: 'false'

      - name: Semantic Release
        uses: ./.github/actions/semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
        
